### ISSUE TITLE
Review the updated README file

### ISSUE THREAD

**Issue by silabozoglu** [course-dprep/top-100-director-impact-on-rating#51]

**Comment by BorisWillekens** [comment]
I think it looks good, however, I think it is missing some explenation on the results. So an explenation on what the graphs say.

**Comment by silabozoglu** [comment]
Thank you for the suggestion! I've added detailed explanations for each graph to clarify better the results they present.

**Comment by BusenazAtahan** [comment]
it looks super cool!

**Comment by Jennicka23** [comment]
This is it, the end! Just like a movie!

**Comment by BusenazAtahan** [comment]
so, im closing this issue. SLEEPWELL GUYS !!!
